# Generated by Django 3.2.7 on 2021-11-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsApp', '0002_auto_20211128_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_list',
            field=models.TextField(blank=True, default='[-1, -2]'),
        ),
    ]
