# Generated by Django 3.2.7 on 2021-11-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsApp', '0003_auto_20211129_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_list',
            field=models.JSONField(blank=True, default='[]'),
        ),
    ]
