# Generated by Django 3.2.7 on 2021-11-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsApp', '0005_alter_user_liked_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(decimal_places=3, default=89.523, max_digits=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=-59.395, max_digits=6),
        ),
    ]
